#!/bin/bash
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/github_rsa

hostfile='hosts'
hosts=`cat $hostfile`

for host in $hosts ; do
  ssh $host 'mkdir ~/ccgraph500logs'
done

for p in 4; do
  for i in {16..16}; do
    echo "$p MPI Processes, scale $i, output_${p}_${i}.log"
    mpirun -np $p --hostfile $hostfile /usr/mpi/examples/graph500_mpi_replicated $i 3>&1 | tee output_${p}_${i}.log ;
    echo "Benchmark was run on $p processes, scale $i" >> output_${p}_${i}.log;
    git add .
    git commit -m "Benchmark $p processes, scale $i"
    git push origin master
  done
done
